### ISSUE TITLE
'DataAPI'がunresolved identifierになる

### ISSUE THREAD

**Issue by hideki-a** [movabletype/mt-data-api-sdk-swift#12]
`import MTDataAPI_SDK`をしても、`Use of unresolved identifier 'DataAPI'`のエラーが発生します。
- SDK 1.0.9
- Xcode 8 (8A218a)
- Use Legacy Swift Language Version: Yes

手動でDataAPI.swiftを配置した場合は問題が発生しません。

ご確認の程お願いいたします。

**Comment by hideki-a** [comment]
FYI:
下記のようにアクセス修飾子を付けることで、`listEntries`は問題なく動作するようになりました。
https://gist.github.com/hideki-a/888dcda71c32732bd5f669a3281cf278/revisions#diff-e70a532615716c6294c36abebc21c065

**Comment by yuji** [comment]
ありがとうございます。

**Comment by hideki-a** [comment]
`pod 'MTDataAPI-SDK', :git => 'https://github.com/movabletype/mt-data-api-sdk-swift.git', :commit => 'fba93e829416a9475c30a48adda240f7979df328'` で fba93e829416a9475c30a48adda240f7979df328 をインストールしアプリのビルドを試したところ、標題のエラーは発生しなくなりました。
ありがとうございます。

**Comment by yuji** [comment]
PRありがとうございました！ 1.0.11 で CoCoaPod にも上げておきます。
